spring.application.name=ApiMonitor
spring.main.web-application-type=servlet
spring.main.keep-alive=true
app.config.path=src/main/resources/config.json
spring.devtools.restart.additional-exclude=**/config.json
